import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One autogenerated sidebar per course.
 * To add a new course: add one line following the same pattern.
 * sidebar_position in each file's frontmatter controls order within the sidebar.
 */
const sidebars: SidebarsConfig = {
  webdevSidebar: [{ type: 'autogenerated', dirName: 'WebDev' }],

  // Add future courses here, e.g.:
  // networkingSidebar: [{ type: 'autogenerated', dirName: 'Networking' }],
  // securitySidebar:   [{ type: 'autogenerated', dirName: 'Security' }],
};

export default sidebars;
