import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One autogenerated sidebar per content type section.
 * Add new courses/sections following the same pattern.
 */
const sidebars: SidebarsConfig = {
  coursesSidebar: [{ type: 'autogenerated', dirName: 'Courses' }],
  unitsSidebar:   [{ type: 'autogenerated', dirName: 'Units' }],
  lessonsSidebar: [{ type: 'autogenerated', dirName: 'Lessons' }],
  projectsSidebar:[{ type: 'autogenerated', dirName: 'Projects' }],
  articlesSidebar:[{ type: 'autogenerated', dirName: 'Articles' }],
  pathwaysSidebar:[{ type: 'autogenerated', dirName: 'Pathways' }],
};

export default sidebars;
